### ISSUE TITLE
success, failure, always, wrap and more not working

### ISSUE THREAD

**Issue by gempir** [jaydubb12/jenkins-dsl-pipelines#1]
My typing for success, failure, always, wrap, lock, sh isn't working 

All of them report "No candidates found for method call"

![image](https://user-images.githubusercontent.com/9765622/189912738-a00d42da-c241-4dfe-bd89-539f09be9eb7.png)

```
pipeline {
    options {
        lock(params.TARGET)
    }
    post {
        success {
            wrap([$class: 'BuildUser']) {

            }
        }

        failure {

        }

    always {
            script {
                sh 'echo hello'
            }
        }
    }
}
```

**Comment by robertoschwald** [comment]
Also, currentBuild cannot be resolved here. It works with https://gist.github.com/ranma2913/6c2424a5bda07d12d034502fb4b0b7c2

**Comment by jaydubb12** [comment]
@robertoschwald thank you for the update / comment...I have updated the jenkins.gdsl as of this 815am EST and the issue should be resolved. 

@gempir Thank you as well for the insight, and feedback. The issues you reported have also been addressed in the same commit.. 

Appreciate the collaboration and time you took to report it!
